language: ruby
cache: bundler
stages:
- unit
- name: integration
  if: type IN (api, cron)
jobs:
  include:
  - stage: unit
    name: unit tests
    script: bundle exec rake test:unit
    rvm:
    - 2.2
    - jruby-9.1.7
  - stage: unit
    name: pronto code review
    script: |
      git remote add upstream https://github.com/gooddata/gooddata-ruby.git
      git fetch upstream master
      bundle exec pronto run -c upstream/master --exit-code
  - stage: integration
    name: lcm integration tests
    script: |
      bundle exec rake -f lcm.rake docker:build
      bundle exec rake -f lcm.rake docker:bundle
      bundle exec rake -f lcm.rake test:integration:docker
    rvm:
    - jruby-9.1.7
  - stage: integration
    name: sdk integration tests
    script: bundle exec rake test:sdk
    rvm: jruby-9.1.7
  - stage: integration
    name: sdk integration tests (project)
    script: bundle exec rake test:project
    rvm: jruby-9.1.7
env:
  global:
  - secure: UR12rfhp90SQDX6JXRXUpEwHgnUAALpn1jIvnQNUU2agXy0ZEtwpXXy7r7WXDHF0wZKrcs1/LytPGk83s3gTrxLV2fxKM6KSSgeizIBlheq5TMCuo00ndrM8qo3bCZFMG5YoGGA5z1vlq/XeSmBNPIc/NhvzE6j5AlxZ3/lw8h4=
